In [1]:
import torch

In [2]:
torch.__version__

'2.3.1+cpu'

In [3]:
import numpy as np

In [4]:
list=[3,4,5,6]
arr = np.array(list)

In [5]:
arr

array([3, 4, 5, 6])

In [6]:
arr.dtype

dtype('int32')

#### Convert Numpy To Pytorch Tensors

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
### Indexing similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [9]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [10]:
### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [11]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [12]:
arr

array([  3,   4,   5, 100])

In [13]:
### prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [14]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [15]:
## zeros and ones
torch.zeros(2,3,dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
torch.ones(2,3,dtype= torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [19]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [20]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

### Arithmetic Operation

In [21]:
a = torch.tensor([3,4,5], dtype= torch.float)
b = torch.tensor([4,5,6], dtype= torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [22]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [23]:
c= torch.zeros(3)

In [24]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [25]:
c

tensor([ 7.,  9., 11.])

In [26]:
#### Some more Operation
a = torch.tensor([3,4,5], dtype= torch.float)
b = torch.tensor([4,5,6], dtype= torch.float)

In [27]:
torch.add(a,b).sum()

tensor(27.)

#### Dot produts and multi Operations

In [28]:
x = torch.tensor([3,4,5], dtype= torch.float)
y = torch.tensor([4,5,6], dtype= torch.float)

In [29]:
x.mul(y)  # 3*4 + 5*4 + 6*5

tensor([12., 20., 30.])

In [30]:
x.dot(y)

tensor(62.)

In [31]:
#### Matrix Multiplication

In [32]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype= torch.float)
y = torch.tensor([[5,6],[8,6],[9,11]], dtype= torch.float)

In [33]:
torch.matmul(x,y)

tensor([[55., 52.],
        [90., 91.]])

In [34]:
torch.mm(x,y)

tensor([[55., 52.],
        [90., 91.]])

In [35]:
x@y

tensor([[55., 52.],
        [90., 91.]])